### ISSUE TITLE
Octave compile error

### ISSUE THREAD

**Issue by Dekalog** [RhysU/ar#26]
When running make I get the following error:

arsel-octfile.cpp:249:5: error: ‘Octave_map’ was not declared in this scope
     Octave_map retval;

and indeed on checking the file I can see that there is no declaration for Octave_map, whereas in arcov-octfile.cpp there is the declaration  

Octave_map arsel1, arsel2;

on line 67. It is not immediately clear to me how I can add the relevant declaration to arsel-octfile.cpp as I am not sure what name to give the declaration and I can see no variables in the main body of code with the map_value() attribute.

**Comment by RhysU** [comment]
The Octave functionality was compiled versus version 3.2.  There may be some case where on version 3.2 the Octave_map declaration was pull in through a transitive #include.  You might dig through the Octave headers to see what to include if you're using a newer Octave version.

That said, I'm (quite literally) three minutes away from ripping out all of the Octave functionality on account of licensing considerations.

**Comment by RhysU** [comment]
Closing as unresolved as I've sunset the Octave API.
