### ISSUE TITLE
test0 kicking back NaNs

### ISSUE THREAD

**Issue by RhysU** [RhysU/ar#28]
Cedric Flageul observed that `test0` is kicking back all NaNs, which it should not.
```
$ ./test test0.coeff test0.dat
         Nominal Value            burg_method           Percent Diff
         -------------            -----------           ------------
                    -1                   -nan                   -nan
                     0                   -nan                   -nan
                     0                   -nan                   -nan
                     0                   -nan                   -nan
                     0                   -nan                   -nan

         mean of data:        9.8765432101235
    \sigma^2_\epsilon:                   -nan
          signal gain:                   -nan
           \sigma^2_x:                   -nan
 Yule-Walker residual:                    nan
```
Need to track how far back the behavior began.  Switching to `-O0` does not seem to address it.

**Comment by RhysU** [comment]
Hurray for Travis-CI keeping old logs around:
 1. Worked in https://travis-ci.org/RhysU/ar/builds/3764577
 2. Did not work in https://travis-ci.org/RhysU/ar/builds/3765682 and seemingly ever since.

Allegedly this means the problem came during  0ff6d5eb4bde039354c1a98f14a86f8838b3a5e7, which I need to review.

**Comment by RhysU** [comment]
Appears to be related to trying to introduce some additional stability as well as not using the Collomb variant.

**Comment by RhysU** [comment]
Changing head of `test0.dat` to be
```
9.87654321012345
9.876543210123456789
9.876543210123456789
```
is enough to recover the former behavior.

**Comment by RhysU** [comment]
First iteration through main ar.hpp#680 loop behaves sanely.  NaN introduced on the second go-round, specifically within mu.

**Comment by RhysU** [comment]
Believe this is now solved appropriately.  Any passers-by feel free to shout if something looks amiss, as high-up fixes for degenerate inputs have a nasty tendency to break downstream edge cases.

**Comment by nicholasmalaya** [comment]
Looks good on my box.
